#!/bin/bash

# pack.sh: Encrypt and wrap executable scripts for secure remote execution
# Usage: ./pack.sh <script_file> > <output_file>

set -euo pipefail

# Check arguments
if [ $# -ne 1 ]; then
    echo "Usage: $0 <script_file>" >&2
    exit 1
fi

SCRIPT_FILE="$1"

# Validate input file
if [ ! -f "$SCRIPT_FILE" ]; then
    echo "Error: '$SCRIPT_FILE' is not a regular file" >&2
    exit 1
fi

if [ ! -r "$SCRIPT_FILE" ]; then
    echo "Error: '$SCRIPT_FILE' is not readable" >&2
    exit 1
fi



# Check if gpg and base64 are available
if ! command -v gpg >/dev/null 2>&1; then
    echo "Error: gpg is required but not installed" >&2
    exit 1
fi

if ! command -v base64 >/dev/null 2>&1; then
    echo "Error: base64 is required but not installed" >&2
    exit 1
fi

# Prompt for password
echo "Enter password for encryption:" >&2
read -s PASSWORD1
echo "" >&2
echo "Confirm password:" >&2
read -s PASSWORD2
echo "" >&2

if [ "$PASSWORD1" != "$PASSWORD2" ]; then
    echo "Error: Passwords do not match" >&2
    exit 1
fi

# Encrypt and base64 encode
ENCRYPTED_PAYLOAD=$(gpg --batch --passphrase "$PASSWORD1" --symmetric --armor --output - "$SCRIPT_FILE" | base64 -w 0)

# Generate wrapper script
cat <<EOF
#!/bin/bash
# Generated by pack.sh - Encrypted script wrapper

set -euo pipefail

# Check for required commands
if ! command -v gpg >/dev/null 2>&1; then
    echo "Error: gpg is required to run this script" >&2
    exit 1
fi

if ! command -v base64 >/dev/null 2>&1; then
    echo "Error: base64 is required to run this script" >&2
    exit 1
fi

# Prompt for decryption password
echo -n "Enter password to decrypt and run the script: " >&2
read -s PASSWORD
echo "" >&2

# Decode and decrypt
DECRYPTED=\$(echo "$ENCRYPTED_PAYLOAD" | base64 -d | gpg --batch --passphrase "\$PASSWORD" --decrypt)

# Write to temp file and execute
TEMP_SCRIPT=\$(mktemp)
trap 'rm -f "\$TEMP_SCRIPT"' EXIT
echo "\$DECRYPTED" > "\$TEMP_SCRIPT"
chmod 0700 "\$TEMP_SCRIPT"
exec "\$TEMP_SCRIPT"
EOF