#!/bin/bash
# Generated by pack.sh - Encrypted script wrapper

set -euo pipefail

# Check for required commands
if ! command -v gpg >/dev/null 2>&1; then
    echo "Error: gpg is required to run this script" >&2
    exit 1
fi

if ! command -v base64 >/dev/null 2>&1; then
    echo "Error: base64 is required to run this script" >&2
    exit 1
fi

# Prompt for decryption password
echo -n "Enter password to decrypt and run the script: " >&2
read -s PASSWORD
echo "" >&2

# Decode and decrypt
DECRYPTED=$(echo "LS0tLS1CRUdJTiBQR1AgTUVTU0FHRS0tLS0tCgpqQTBFQ1FNSzViNGRheTVaZjFULzBsWUJWZWVRdS9zR2xrTEFHWEtzcVVoUDRzbks3ZUJLVVNUdVNTR1N1eGJ4Ck1wMmFEZjNrRnpSMmtkazZudXN5aUlkWVlldnMrQVdNb2tPam81Nnhoa2h6dTBodzVCRkw2alk2MlBJQXNKcnIKRzdGNG9zMlZ5Zz09Cj1lT0JLCi0tLS0tRU5EIFBHUCBNRVNTQUdFLS0tLS0K" | base64 -d | gpg --batch --passphrase "$PASSWORD" --decrypt)

# Write to temp file and execute
TEMP_SCRIPT=$(mktemp)
trap 'rm -f "$TEMP_SCRIPT"' EXIT
echo "$DECRYPTED" > "$TEMP_SCRIPT"
chmod 0700 "$TEMP_SCRIPT"
exec "$TEMP_SCRIPT"
